--------------------------------------------------------
--  DDL for Table MOVIMENTO
--------------------------------------------------------

  CREATE TABLE "CATRACA"."MOVIMENTO" 
   (	"CD_MATRICULA" VARCHAR2(20 BYTE), 
	"DS_NOME" VARCHAR2(255 BYTE), 
	"DT_MOVIMENTO" DATE, 
	"DS_TIPO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TABELA" ;
--------------------------------------------------------
--  DDL for Table COLABORADORES
--------------------------------------------------------

  CREATE TABLE "CATRACA"."COLABORADORES" 
   (	"CD_MAT_CAT" VARCHAR2(20 BYTE), 
	"DS_NOME_CAT" VARCHAR2(255 BYTE), 
	"CD_COLIGADA" NUMBER, 
	"CD_CPF" VARCHAR2(15 BYTE), 
	"CD_SECAO" VARCHAR2(15 BYTE), 
	"CD_CC" VARCHAR2(11 BYTE), 
	"CD_SITUACAO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TABELA" ;
--------------------------------------------------------
--  DDL for Index COLABORADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CATRACA"."COLABORADORES_PK" ON "CATRACA"."COLABORADORES" ("CD_MAT_CAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TABELA" ;
--------------------------------------------------------
--  Constraints for Table COLABORADORES
--------------------------------------------------------

  ALTER TABLE "CATRACA"."COLABORADORES" ADD CONSTRAINT "COLABORADORES_PK" PRIMARY KEY ("CD_MAT_CAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TABELA"  ENABLE;
 
  ALTER TABLE "CATRACA"."COLABORADORES" MODIFY ("CD_MAT_CAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MOVIMENTO
--------------------------------------------------------

  ALTER TABLE "CATRACA"."MOVIMENTO" ADD CONSTRAINT "MOVIMENTO_FK1" FOREIGN KEY ("CD_MATRICULA")
	  REFERENCES "CATRACA"."COLABORADORES" ("CD_MAT_CAT") ENABLE;
