--------------------------------------------------------
--  DDL for Table ACESSO_LINHA
--------------------------------------------------------

  CREATE TABLE "TELEFONIA"."ACESSO_LINHA" 
   (	"ID_ACESSO_LINHA" NUMBER, 
	"CD_CPF_AGENTE" VARCHAR2(15 BYTE), 
	"CD_LINHA" VARCHAR2(20 BYTE), 
	"SDEL" CHAR(1 BYTE), 
	"CREATEBY" VARCHAR2(45 BYTE), 
	"CREATEIN" DATE, 
	"UPDATEBY" VARCHAR2(45 BYTE), 
	"UPDATEIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TABELA" ;
--------------------------------------------------------
--  DDL for Table EXTRATO
--------------------------------------------------------

  CREATE TABLE "TELEFONIA"."EXTRATO" 
   (	"NUMNF" VARCHAR2(20 BYTE), 
	"NUMIDCLI" VARCHAR2(12 BYTE), 
	"MESREF" VARCHAR2(6 BYTE), 
	"NUMACS" VARCHAR2(20 BYTE), 
	"PLANO" VARCHAR2(150 BYTE), 
	"NOME" VARCHAR2(150 BYTE), 
	"TPSERV" VARCHAR2(150 BYTE), 
	"DATA" VARCHAR2(8 BYTE), 
	"HORA" VARCHAR2(8 BYTE), 
	"ORIGEM" VARCHAR2(80 BYTE), 
	"DESTINO" VARCHAR2(120 BYTE), 
	"NUMCHAM" VARCHAR2(20 BYTE), 
	"TIPO" VARCHAR2(5 BYTE), 
	"DURACAO" VARCHAR2(50 BYTE), 
	"VALOR" NUMBER(15,2), 
	"OPERLD" VARCHAR2(10 BYTE), 
	"TIMID" VARCHAR2(10 BYTE), 
	"ALIQUOTA" VARCHAR2(10 BYTE), 
	"CODFEBRABAN" VARCHAR2(200 BYTE), 
	"TOTALGERAL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TABELA" ;
--------------------------------------------------------
--  DDL for Table LINHA_CELULAR
--------------------------------------------------------

  CREATE TABLE "TELEFONIA"."LINHA_CELULAR" 
   (	"ID" NUMBER, 
	"CPF" VARCHAR2(15 BYTE), 
	"LINHA" VARCHAR2(20 BYTE), 
	"DATAINCLUSO" DATE, 
	"USUARIO" VARCHAR2(50 BYTE), 
	"DESC_FOLHA" CHAR(1 BYTE), 
	"CCEO" VARCHAR2(15 BYTE), 
	"UPDATEBY" VARCHAR2(45 BYTE), 
	"UPDATEIN" DATE, 
	"SDEL" CHAR(1 BYTE), 
	"DS_TIPO" VARCHAR2(20 BYTE), 
	"DS_NOME" VARCHAR2(75 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TABELA" ;
--------------------------------------------------------
--  DDL for Table SA_EXTRATO
--------------------------------------------------------

  CREATE TABLE "TELEFONIA"."SA_EXTRATO" 
   (	"NUMNF" VARCHAR2(255 BYTE), 
	"NUMIDCLI" VARCHAR2(255 BYTE), 
	"MESREF" VARCHAR2(255 BYTE), 
	"NUMACS" VARCHAR2(255 BYTE), 
	"PLANO" VARCHAR2(255 BYTE), 
	"NOME" VARCHAR2(255 BYTE), 
	"TPSERV" VARCHAR2(255 BYTE), 
	"DATA" VARCHAR2(255 BYTE), 
	"HORA" VARCHAR2(255 BYTE), 
	"ORIGEM" VARCHAR2(255 BYTE), 
	"DESTINO" VARCHAR2(255 BYTE), 
	"NUMCHAM" VARCHAR2(255 BYTE), 
	"TIPO" VARCHAR2(255 BYTE), 
	"DURACAO" VARCHAR2(255 BYTE), 
	"VALOR" VARCHAR2(255 BYTE), 
	"OPERLD" VARCHAR2(255 BYTE), 
	"TIMID" VARCHAR2(255 BYTE), 
	"ALIQUOTA" VARCHAR2(255 BYTE), 
	"CODFEBRABAN" VARCHAR2(255 BYTE), 
	"TOTALGERAL" VARCHAR2(255 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "ETL"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY '\n'   
SKIP 1    
FIELDS TERMINATED BY ';'
MISSING FIELD VALUES ARE NULL
    )
      LOCATION
       ( "ETL":'FAT201604.TXT'
       )
    )
   REJECT LIMIT UNLIMITED;
--------------------------------------------------------
--  DDL for Index ACESSO_LINHA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TELEFONIA"."ACESSO_LINHA_PK" ON "TELEFONIA"."ACESSO_LINHA" ("ID_ACESSO_LINHA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TABELA" ;
--------------------------------------------------------
--  DDL for Index LINHA_CELULAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TELEFONIA"."LINHA_CELULAR_PK" ON "TELEFONIA"."LINHA_CELULAR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TABELA" ;
--------------------------------------------------------
--  Constraints for Table ACESSO_LINHA
--------------------------------------------------------

  ALTER TABLE "TELEFONIA"."ACESSO_LINHA" ADD CONSTRAINT "ACESSO_LINHA_PK" PRIMARY KEY ("ID_ACESSO_LINHA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TABELA"  ENABLE;
 
  ALTER TABLE "TELEFONIA"."ACESSO_LINHA" MODIFY ("ID_ACESSO_LINHA" NOT NULL ENABLE);
 
  ALTER TABLE "TELEFONIA"."ACESSO_LINHA" MODIFY ("CD_CPF_AGENTE" NOT NULL ENABLE);
 
  ALTER TABLE "TELEFONIA"."ACESSO_LINHA" MODIFY ("CD_LINHA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LINHA_CELULAR
--------------------------------------------------------

  ALTER TABLE "TELEFONIA"."LINHA_CELULAR" ADD CONSTRAINT "LINHA_CELULAR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TABELA"  ENABLE;
 
  ALTER TABLE "TELEFONIA"."LINHA_CELULAR" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TELEFONIA"."LINHA_CELULAR" MODIFY ("LINHA" NOT NULL ENABLE);
